import { Injectable } from '@angular/core';
import {EnquiryLineItem} from '../Domain/enquiry';

@Injectable({
  providedIn: 'root',
})
export class EnquiryNestedTreeService {
  constructor() {}

  getEnquiryLineItemsData() :EnquiryLineItem[] {
     return [
      {
        id: 1,
        s_no: 1,
        quantity: 10,
        type: 'Type A',
        service_area: 'service area 1',
        basis: '20ft',
        remarks: 'enquiry line item remarks 1',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 1,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 1,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
      {
        id: 2,
        s_no: 2,
        quantity: 8,
        type: 'Type B',
        service_area: 'service area 2',
        basis: '20ft',
        remarks: 'enquiry line item remarks 2',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 2,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 2,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
      {
        id: 3,
        s_no: 3,
        quantity: 1,
        type: 'Type c',
        service_area: 'service area 3',
        basis: '20ft',
        remarks: 'enquiry line item remarks 3',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 3,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 3,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
    ];
  }
  enquiryLineItemData: EnquiryLineItem[] =[
      {
        id: 1,
        s_no: 1,
        quantity: 10,
        type: 'Type A',
        service_area: 'service area 1',
        basis: '20ft',
        remarks: 'enquiry line item remarks 1',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 1,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 1,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
      {
        id: 2,
        s_no: 2,
        quantity: 8,
        type: 'Type B',
        service_area: 'service area 2',
        basis: '20ft',
        remarks: 'enquiry line item remarks 2',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 2,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 2,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
      {
        id: 3,
        s_no: 3,
        quantity: 1,
        type: 'Type c',
        service_area: 'service area 3',
        basis: '20ft',
        remarks: 'enquiry line item remarks 3',
        sourcing_summary: [
          {
            id: 1,
            enquiry_line_item_id: 3,
            source_type: 'sourcing',
            sourced_no: 2,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'Vendor 1',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 1',
                to_location: 'to loc 1',
                currency: 'INR',

                basis: '20ft',
                charges: 40,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'Vendor 2',
                vendor_type: 'Type B',
                mode: 'export',
                from_location: 'from loc 2',
                to_location: 'to loc 2',
                currency: 'INR',

                basis: '40ft',
                charges: 41,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'Vendor 3',
                vendor_type: 'Type A',
                mode: 'export',
                from_location: 'from loc 3',
                to_location: 'to loc 3',
                currency: 'USD',

                basis: '58ft',
                charges: 42,
                start_date: '10-1-25',
                end_date: '10-1-26',
                effective_date: '10-22-25',
              },
            ],
          },
          {
            id: 2,
            enquiry_line_item_id: 3,
            source_type: 'tariff',
            sourced_no: 3,
            sourced_list: [
              {
                id: 1,
                vendor_code: 'ven-1',
                vendor_name: 'vendor 1',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 1',
                to_location: 'to location 1',
                charges: 11,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 2,
                vendor_code: 'ven-2',
                vendor_name: 'vendor 2',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 2',
                to_location: 'to location 2',
                charges: 12,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
              {
                id: 3,
                vendor_code: 'ven-3',
                vendor_name: 'vendor 3',
                vendor_type: 'vendor type',
                mode: 'export',
                from_location: 'from location 3',
                to_location: 'to location 3',
                charges: 13,
                effective_date: '10-01-25',
                expiry_date: '10-01-26',
                mandatory: true,
              },
            ],
          },
        ],
        status: 'active',
      },
    ]

  getEnquiryLineItems() {
    return Promise.resolve(this.enquiryLineItemData);
  }
}
